website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from . import db
import json

from .models import Question, Answer, Reply, User
views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("home.html", user=current_user)

@views.route('/terms_of_service')
def  terms_of_service():
    return render_template('terms_of_service.html', user=current_user)

@views.route('/privacy_policy')
def  privacy_policy():
    return render_template('privacy_policy.html', user=current_user)  
@views.route('/help')
@login_required
def help():
    return render_template("help.html",user=current_user)

@views.route('/profile', methods=['GET','POST'])
@login_required
def profile():
    if  request.method == "POST":
        flash('Password succesfully!',category='success')
        return render_template('home.html',user=current_user)
    game=Game.query.filter_by(user_id=current_user.id).first()
    return render_template('profile.html',user=current_user,game=game)

@views.route('/leaderboard')
@login_required
def leaderboard():
    users = db.session.query(Game.user_id, (Game.won / (Game.played - Game.won)).label('win_loss_ratio')).all()
    sorted_users = sorted(users, key=lambda x: x.win_loss_ratio, reverse=True)
    top_user = sorted_users[0] if sorted_users else None
    return render_template('leaderboard.html', user=current_user,top_user=top_user, sorted_users=sorted_users)

@views.route('/messages')
@login_required
def messages():
    
    messages = db.session.query(Message.content, User.first_name).join(User).all()
    return render_template('messages.html', messages=messages, user=current_user)

from .models import db, Message
from .forms import ContactForm

@views.route('/support', methods=['GET', 'POST'])
@login_required
def support():
    if request.method == 'POST':
        message_content = request.form.get('message')
        if message_content:
            try:
                # Create a new Message instance
                new_message = Message(content=message_content, user_id=current_user.id)
                db.session.add(new_message)
                db.session.commit()
                flash('Your message has been sent!', category='success')
                return redirect(url_for('views.support'))
            except Exception as e:
                flash('An error occurred while sending your message. Please try again.', category='error')
                print(f"Error sending message: {e}")  # Print the error to debug
        else:
            flash('Message cannot be empty!', category='error')
    return render_template("support.html", user=current_user)

@views.route('/forum')
@login_required
def forum():
    questions = Question.query.all()
    return render_template("forum.html", questions=questions, user=current_user)

@views.route('/forum/question/<int:question_id>', methods=['GET', 'POST'])
@login_required
def view_question(question_id):
    question = Question.query.get_or_404(question_id)
    answers = Answer.query.filter_by(question_id=question_id).all()      
    if request.method == 'POST':
        answer_content = request.form.get('content')
        if answer_content:
            try:
                new_answer = Answer(content=answer_content, question_id=question.id, user_id=current_user.id)
                db.session.add(new_answer)
                db.session.commit()
                flash('Your answer has been posted!', category='success')
                return redirect(url_for('views.view_question', question_id=question.id))
            except Exception as e:
                flash('An error occurred while posting your answer. Please try again.', category='error')
                views.logger.error(f"Error posting answer: {e}")
        else:
            flash('Answer cannot be empty!', category='error')    
    return render_template("view_question.html", question=question, answers=answers, user=current_user)


@views.route('/forum/reply/<int:answer_id>', methods=['POST'])
@login_required
def post_reply(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    reply_content = request.form.get('content')
    if reply_content:
        new_reply = Reply(content=reply_content, answer_id=answer.id, user_id=current_user.id)
        db.session.add(new_reply)
        db.session.commit()
        flash('Your reply has been posted!', category='success')
    else:
        flash('Reply cannot be empty!', category='error')
    return redirect(url_for('views.view_question', question_id=answer.question.id))


@views.route('/forum/answers/<int:question_id>')
@login_required
def view_answers(question_id):
    question = Question.query.get_or_404(question_id)
    answers = Answer.query.filter_by(question_id=question_id).all()
    return render_template("view_answers.html", question=question, answers=answers, user=current_user)




@views.route('/submit-question', methods=['GET', 'POST'])
@login_required
def submit_question():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        if title and content:
            new_question = Question(title=title, content=content, user_id=current_user.id)
            db.session.add(new_question)
            db.session.commit()
            flash('Your question has been submitted!', category='success')
            return redirect(url_for('views.forum'))
        else:
            flash('Title and content cannot be empty!', category='error')
    return render_template("submit_question.html", user=current_user)



from .models import Game
@views.route('/startgame', methods=['GET', 'POST'])
@login_required
def startgame():
    if request.method == 'POST':
        data = request.json
        if data:
            received_data = data.get('data')
            x_won=0
            x_lose=0
            x_draw=0
            if received_data:
                print('Received data from JS:', received_data)
                
                game = Game.query.filter_by(user_id=current_user.id).first()
                if received_data=='You Win':
                    x_won=1
                elif received_data=='Draw':
                    x_draw=1
                else:
                    x_lose=1
                if game:
                    # If user exists, update the played and won counts
                    game.played += 1
                    if x_won:
                        game.won += x_won
                    elif x_draw:
                        game.draw += x_draw                    
                else:
                    game = Game(user_id=current_user.id, played=1, won=x_won, draw=x_draw)
                    db.session.add(game)

                db.session.commit()
                            
                return jsonify({'message': 'Data received successfully'}), 200
            else:
                return jsonify({'error': 'Data key not found in JSON'}), 400
        else:
            return jsonify({'error': 'Invalid JSON format or no data provided'}), 400
    # If it's a GET request, render the startgame.html template
    return render_template('startgame.html', user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"/>
    
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="profile" href="/profile">Profile</a>
          <a class="nav-item nav-link" id="help" href="/help">Help</a>
          <a class="nav-item nav-link" id="leaderboard" href="/leaderboard">Leader-board</a>
          {% if current_user.id == 1 %}
                <a class="nav-item nav-link" id="messages" href="/messages">Messages</a>
            {% endif %}
          <a class="nav-item nav-link" id="forum" href="/forum">Forum</a>
          <a class="nav-item nav-link" id="support" href="/support">Community</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}

        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}

<footer class="footer">
  <div class="container">
      <div class="row">
          <div class="col-md-6">
              <h5>Contact Information</h5>
              <p>Email: <a href="mailto:harishreddychilumula7@gmail.com">harishreddychilumula7@gmail.com</a></p>
              <p>Phone: <a href="tel:+917013873682">+91 7013873682</a></p>
          </div>
          <div class="col-md-6">
              <h5>Follow Me</h5>
              <ul class="list-inline">
                  <li class="list-inline-item"><a href="https://www.facebook.com/harishreddy.ch/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                  <li class="list-inline-item"><a href="https://www.linkedin.com/in/harish-reddy-chilumula/" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                  <li class="list-inline-item"><a href="https://www.instagram.com/harish_reddy_0007/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                  <li class="list-inline-item"><a href="https://twitter.com/harishreddych_7" target="_blank"><i class="fa fa-twitter"></i></a></li>
                  <li class="list-inline-item"><a href="https://github.com/HARISHREDDYCHILUMULA" target="_blank"><i class="fa fa-github"></i></a></li>
              </ul>
          </div>
      </div>
      <div class="row">
          <div class="col-md-12">
              <p class="text-muted small mb-0">Connect 4 Web App - &copy; 2024 - All rights reserved</p>
              <p class="text-muted small mb-0"><a href="/privacy_policy">Privacy Policy</a> | <a href="/terms_of_service">Terms of Service</a></p>
          </div>
      </div>
  </div>
</footer>


  </body>

</html>

website/templates/confirm_logout.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Confirm Logout</title>
</head>
<body>
    <h2>Confirm Logout</h2>
    <p>Are you sure you want to log out?</p>
    <form method="post">
        <button type="submit">Yes, Log Out</button>
        <a href="{{ url_for('views.home') }}">No, Go Back</a>
    </form>
</body>
</html>
{% endblock %}

website/templates/help.html
{% extends "base.html" %}
{% block title %}Help{% endblock %}
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f2f2f2;
    }

    .container {
        max-width: 800px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
    }

    p {
        line-height: 1.6;
    }

    .step {
        margin-bottom: 30px;
    }

    .step h2 {
        margin-bottom: 10px;
    }

    .step img {
        display: block;
        margin: 0 auto;
        max-width: 100%; /* Ensure images are responsive and fit within container */
        height: auto; /* Maintain aspect ratio */
    }

    .step p {
        margin-top: 10px;
    }

    .btn {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s ease;
    }

    .btn:hover {
        background-color: #0056b3;
    }
    .rules {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        ol {
            padding-left: 20px;
        }
</style>
<div class="container">
    <h1>Connect 4 Tutorial</h1>
    
    <div class="step">
        <h2>Step 1: Start the Game</h2>
        <img src="/static/images/starting.jpeg" alt="Start Game">
        <p>Start the Connect 4 game by clicking on the 'Play' button.</p>
    </div>
    
    <div class="step">
        <h2>Step 2: Drop Tokens</h2>
        <img src="/static/images/dropping.jpeg" alt="Drop Tokens">
        <p>Take turns with your opponent to drop your colored tokens into the columns. The goal is to connect four of your tokens vertically, horizontally, or diagonally.</p>
    </div>
    
    <div class="step">
        <h2>Step 3: Win the Game</h2>
        <img src="/static/images/winning.jpeg" alt="Win Game">
        <p>If you successfully connect four of your tokens, you win the game! If the board fills up before either player achieves four in a row, the game is a draw.</p>
    </div>
    <div class="rules">
        
        <h2>Rules:</h2>
        <ol>
            <li>The game is played on a adjustable grid initially consists of 12 columns wide and 8 rows high.</li>
            <li>Players take turns dropping one colored disc (red or yellow in random) from the top into the grid.</li>
            <li>The pieces fall straight down, occupying the lowest available space within the column.</li>
            <li>The game continues until one player forms a line of four of their own colored discs horizontally, vertically, or diagonally.</li>
            <li>If the grid is filled with discs and no player has won, the game is a draw.</li>
        </ol>

        <p>For more detailed rules and strategies, you can refer to the official Connect 4 rulebook or online resources.</p>
    </div>
    <p>Ready to play? Click the button below to start!</p>
    <a href="/startgame" class="btn">Play Connect 4</a>
</div>
{% endblock %}

website/templates/home.html
<!-- home.html -->
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<style>
    /* Style for container */
    .container {
        margin-top: 50px;
    }

    /* Style for feature section */
    .feature-section {
        margin-top: 20px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    /* Style for buttons */
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
        transition: background-color 0.3s ease, border-color 0.3s ease;
        animation: fadeInUp 0.5s ease;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }

    .btn-lg {
        padding: 10px 20px;
        font-size: 1.2rem;
        border-radius: 5px;
        text-transform: uppercase;
        font-weight: bold;
        letter-spacing: 1px;
        transition: all 0.3s ease;
    }

    /* Keyframes for fadeInUp animation */
    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    /* Background animation */
    @keyframes changeBackgroundColor {
        0% {
            background-color: #007bff;
        }
        50% {
            background-color: #0056b3;
        }
        100% {
            background-color: #007bff;
        }
    }

    /* Apply background animation to buttons */
    .animated-background {
        animation: changeBackgroundColor 3s infinite;
    }

    /* Style for responsiveness */
    @media (max-width: 768px) {
        .col-md-7 {
            order: 2;
        }

        .col-md-5 {
            order: 1;
        }
    }

</style>
<div class="container">
    <div class="row">
      
        <!-- Feature Section -->
        <div class="col-md-5">
            <div class="feature-section">
                <a href="/startgame" class="btn btn-primary btn-lg animated-background">Play Connect 4</a>
                <a href="/statistics" class="btn btn-primary btn-lg animated-background">Statistics</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/leaderboard.html
{% extends "base.html" %}
{% block title %}Leaderboard{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaderboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f8f8;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1, h2 {
            color: #333;
        }

        .top-user {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f0f0f0;
            border-radius: 5px;
        }

        .leaderboard-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .leaderboard-table th, .leaderboard-table td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        .leaderboard-table th {
            background-color: #f0f0f0;
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Leaderboard</h1>

        {% if top_user %}
        <div class="top-user">
            <h2>Top User</h2>
            <p>User Name: 
                {% set usercur = user.query.get(top_user.user_id) %}
                {% if usercur %}
                    {{ usercur.first_name }}
                {% else %}
                    User Not Found
                {% endif %}
            </p>
            <p>Win/Loss Ratio: {{ top_user.win_loss_ratio }}</p>
        </div>
        {% else %}
        <p>No users found.</p>
        {% endif %}

        <h2>All Users</h2>
        <table class="leaderboard-table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>User Name</th>
                    <th>Win/Loss Ratio</th>
                </tr>
            </thead>
            <tbody>
                {% for iuser in sorted_users %}
                    {% set user_obj = user.query.get(iuser.user_id) %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ user_obj.first_name if user_obj else 'User Not Found' }}</td>
                        <td>{{ iuser.win_loss_ratio }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</body>
</html>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<style>
    .container {
        max-width: 600px;
        margin: 50px auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    
    .profile-info {
        text-align: center;
        margin-bottom: 30px;
    }
    
    .profile-pic {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        object-fit: cover;
        border: 3px solid #fff; /* Add a border to the profile picture */
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.3); /* Add a shadow effect */
    }
    
    .profile-name {
        margin-top: 10px;
        font-size: 24px;
        color: #333;
    }
    
    .profile-email {
        color: #666;
        margin-bottom: 20px;
    }
    
    .stats {
        margin-bottom: 30px;
    }
    
    .stats-item {
        margin-bottom: 15px;
        font-size: 16px;
        color: #333;
    }
    
    .change-password-form {
        margin-top: 30px;
    }
    
    .change-password-form h3 {
        margin-bottom: 15px;
        font-size: 20px;
        color: #333;
    }
    
    .change-password-form label {
        display: block;
        margin-bottom: 8px;
        color: #333;
    }
    
    .change-password-form input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
    }
    
    .change-password-form input[type="submit"] {
        display: block;
        width: 100%;
        padding: 12px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }
    
    .change-password-form input[type="submit"]:hover {
        background-color: #0056b3;
    }
    
    .logout-btn {
        display: block;
        width: 100%;
        padding: 12px;
        background-color: #dc3545;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        text-align: center;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }
    
    .logout-btn:hover {
        background-color: #c82333;
    }
</style>

<div class="container">
    <div class="profile-info">
        <!-- <img src="" alt="Profile Picture" class="profile-pic"> -->
        <div class="profile-name">User: {{ user.first_name }}</div>
        <div class="profile-email">Email: {{ user.email }}</div>
    </div>
    
    <div class="stats">
        <div class="stats-item">
            <strong>Total Games Played: {{game.played}}</strong>
        </div>
        <div class="stats-item">
            <strong>Win/Loss Ratio:{%if game.played- game.won !=0:%}
                {{game.won/(game.played-game.won)}}
                {%else:%}
                {{'N/A'}}
                {%endif%}
            </strong>
        </div>
        
    </div>
    
    <div class="change-password-form">
        <h3>Change Password</h3>
        <form action="/changepassword" method="post">
            <label for="current-password">Current Password:</label>
            <input type="password" id="current-password" name="current-password" required>
            <label for="new-password">New Password:</label>
            <input type="password" id="new-password" name="new-password" required>
            <label for="confirm-password">Confirm Password:</label>
            <input type="password" id="confirm-password" name="confirm-password" required>
            <input type="submit" value="Change Password">
        </form>
    </div>
    
    <a href="/logout" class="logout-btn">Logout</a>
</div>
{% endblock %}

website/templates/submit_question.html
<!-- submit_question.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Submit a Question</h2>
  
  <form method="post" action="{{ url_for('views.submit_question') }}">
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" id="title" name="title" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="content">Content</label>
      <textarea id="content" name="content" class="form-control" rows="5" required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

website/templates/view_answers.html
<!--view_answers.html-->
{% extends 'base.html' %}

{% block content %}
  <h2>{{ question.title }}</h2>
  <p>{{ question.content }}</p>
  <p>Posted by: {{ question.user.first_name }}</p>
  
  <hr>
  
  <h3>Answers</h3>
  
  {% for answer in answers %}
    <div class="answer">
      <p>{{ answer.content }}</p>
      <p>Posted by: {{ answer.user.first_name }}</p>
      
      <h4>Replies</h4>
      {% for reply in answer.replies %}
        <div class="reply">
          <p>{{ reply.content }}</p>
          <p>Posted by: {{ reply.user.first_name }}</p>
        </div>
      {% endfor %}
    </div>
    <hr>
  {% endfor %}
  
  
{% endblock %}

website/templates/view_question.html
{% extends 'base.html' %}

{% block content %}
<style>
  /* Custom styles for view_question.html */

/* Main container */
.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

/* Question title */
h2 {
  font-size: 24px;
  color: #333;
}

/* Question content */
p {
  font-size: 16px;
  color: #555;
}

/* Posted by */
.post-info {
  font-size: 14px;
  color: #888;
}

/* Answers section */
.answer {
  margin-bottom: 20px;
  padding: 10px;
  background-color: #f9f9f9;
  border-radius: 5px;
}

/* Reply form */
.reply-form {
  margin-top: 10px;
}

/* Reply button */
.reply-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
}

.reply-button:hover {
  background-color: #0056b3;
}

/* Newly submitted answer */
.new-answer {
  margin-top: 20px;
  padding: 10px;
  background-color: #f0f0f0;
  border-radius: 5px;
}

/* Form input fields */
textarea {
  width: 100%;
  height: 100px;
  margin-bottom: 10px;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: none;
}

/* Submit button */
.submit-button {
  background-color: #28a745;
  color: #fff;
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
}

.submit-button:hover {
  background-color: #218838;
}

</style>
<h2>{{ question.title }}</h2>
<p>{{ question.content }}</p>
<p>Posted by: {{ question.user.first_name }}</p>
  
<hr>
  

  
{% for answer in answers %}
<h3>Answer</h3>
  <div class="answer">
    <p>{{ answer.content }}</p>
    <p>Posted by: {{ answer.user.first_name }}</p>
    
    {% if answer.replies %}  <!-- Check if there are replies -->
      <h4>Replies</h4>
      {% for reply in answer.replies %}
        <div class="reply">
          <p>{{ reply.content }}</p>
          <p>Posted by: {{ reply.user.first_name }}</p>
        </div>
      {% endfor %}
    {% endif %}
    
    <form method="post" action="{{ url_for('views.post_reply', answer_id=answer.id) }}">
      <textarea name="content" placeholder="Reply to this answer" required></textarea>
      <button type="submit">Reply</button>
    </form>
  </div>
  <hr>
{% endfor %}

<!-- Display the newly submitted answer -->
{% if new_answer %}
  <div class="answer">
    <p>{{ new_answer.content }}</p>
    <p>Posted by: {{ new_answer.user.first_name }}</p>
    <!-- You can also include a form for replies to this answer if needed -->
  </div>
  <hr>
{% endif %}

<form method="post" action="{{ url_for('views.view_question', question_id=question.id) }}">
  <textarea name="content" placeholder="Your answer" required></textarea>
  <button type="submit">Post Answer</button>
</form>

{% endblock %}